### PR TITLE
Final implementation: Screensharing for android, ios and partially windows.

### PR DESCRIPTION
**Pull request by andersonvieiragomeslopes**
@tompi 

Android: OK

Android OK

iOS: OK, but it doesn't work with the app in the background, it's possible to share screen only with the transmitter app activated, microsoft intends to fix this limitation through an extension, so I added another project (TestSample.iOS.ScreensharingExtension) to the solution, it will help thereby.

Windows: It is necessary to wait for the next version of the sdk because the method to start the screensharing is not available.

P.S: I haven't added an on-screen button to use the feature yet, but it's in the roadmap.

### CODE REVIEW

**Comment by tompi** [comment]
Hey @andersonvieiragomeslopes 

Im sure this is fine, but just wondering about the commented out code mentioning the CallClientHelper:

'''
CallClientHelper.FillFrame
'''

Are you waiting for something in the helper?

**Comment by andersonvieiragomeslopes** [comment]
> Hey @andersonvieiragomeslopes
> 
> Im sure this is fine, but just wondering about the commented out code mentioning the CallClientHelper:
> 
> ''' CallClientHelper.FillFrame '''
> 
> Are you waiting for something in the helper?

Hi, @tompi.

This serves to send custom frames, for example: transmit frames of some byte array, but honestly I don't know if anyone would have a specific case like that.

**Comment by tompi** [comment]
Another thing I was thinking about, I suppose we should have a two branches more, one for beta and one for alpha?

This wound make it much easier to maintain nugets of alpha/beta/official at the same time...

If you agree, i will branch out next time ms releases something new.

**Comment by andersonvieiragomeslopes** [comment]
> 

Of course, it would be great!

**Pull request merged**
