### PR TITLE
New example implementation with more features

### PR DESCRIPTION
**Pull request by andersonvieiragomeslopes**
@tompi  evaluate if readme.md is good in the way it is organized and if I have neglected to mention information that you consider relevant.

### CODE REVIEW

**Comment by tompi** [comment]
Thank you, Looks like you put in a lot of effort! Ill review and merge once Im back from vacation

**Comment by andersonvieiragomeslopes** [comment]
> Thank you, Looks like you put in a lot of effort! Ill review and merge once Im back from vacation

Obrigado, boas férias.

**Comment by tompi** [comment]
Hey, this looks really good.

still checking out the example app, but a few notes on the readme:
I think we should still mention the binding library first, the sample app is meant to demonstrate/test usage...(small detail: remove leading / in image urls, they will then work locally as well)

i dont understand the uwp project, is this a working demo? i dont have a windows machine here, but i cant see any reference to https://www.nuget.org/packages/Azure.Communication.Calling ?

you should also delete/replace the old example app, we dont need two?
(i think exampleapp is better name than azuresample, or maybe just sampleapp/sample or demo...)

ps, got the app running on ios now, looks really slick!

**Comment by andersonvieiragomeslopes** [comment]
> Hey, this looks really good.
> 
> still checking out the example app, but a few notes on the readme: I think we should still mention the binding library first, the sample app is meant to demonstrate/test usage...(small detail: remove leading / in image urls, they will then work locally as well)

I'll fix the project name, this is pretty tedious ;( but I think it makes sense to define a better naming.
About the readme I will make the changes, really, it is important to mention this information.

> 
> i dont understand the uwp project, is this a working demo? i dont have a windows machine here, but i cant see any reference to https://www.nuget.org/packages/Azure.Communication.Calling ?
> 
> you should also delete/replace the old example app, we dont need two? (i think exampleapp is better name than azuresample, or maybe just sampleapp/sample or demo...)
> 

Well, you idealized all this, I didn't feel comfortable deleting your great work :)

> ps, got the app running on ios now, looks really slick!

**Comment by andersonvieiragomeslopes** [comment]
@tompi Changes have been made.

**Comment by andersonvieiragomeslopes** [comment]
@tompi  Could you enable discussions to make communication a little faster? There are many things that are not needed tickets in the problems tab, that is, questions, the option is in the repository settings.

image

**Comment by tompi** [comment]
thnx, about the readme, I just felt that it was mostly about the sample app, and not so much about the binding libraries :)

If you are comfortable with it, I can merge and then add a few words about the binding?

**Comment by andersonvieiragomeslopes** [comment]
> thnx, about the readme, I just felt that it was mostly about the sample app, and not so much about the binding libraries :)
> 
> If you are comfortable with it, I can merge and then add a few words about the binding?

Yes, we can, feel free to submit changes.

**Comment by andersonvieiragomeslopes** [comment]
I'm creating a plugin to work with xamarin.forms, soon information about the binding won't be that important anymore, I want to make it plug and play for use with forms.

**Pull request merged**
