### PR TITLE
Bump azure communication calling to stable version 2.8.0

### PR DESCRIPTION
**Pull request by kmiterror**

### CODE REVIEW

**Comment by kmiterror** [comment]
@tompi shall we merge it and publish stable package?

**Comment by tompi** [comment]
@kmiterror I made some minor changes to compile, and released an untested(....) version to nuget.
Let me know if it works, and I will merge the pr.

**Comment by tompi** [comment]
@kmiterror you know what, since I already published npm, Ill just merge...

**Comment by kmiterror** [comment]
I did a round of testing and all seems good. 
We will do more testing and soon will release it out to the wild.
So far we use 2.8.0-beta.1.2 in production for few days and it seems that it's quite ok.

**Pull request merged**
