### PR TITLE
Screensharing implementation for android

### PR DESCRIPTION
**Pull request by andersonvieiragomeslopes**

### CODE REVIEW

**Comment by andersonvieiragomeslopes** [comment]
@tompi I believe there was a need to publish a version for the helper as well, I have a local copy here that already has the improvements I made in PR for screensharing in case you want to take advantage of it.


[Xamarin.AzureCommunicationCallingHelper.Android.2.4.0-beta.5.zip](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/files/9778371/Xamarin.AzureCommunicationCallingHelper.Android.2.4.0-beta.5.zip)

**Comment by tompi** [comment]
hey @andersonvieiragomeslopes, seems like this pr is marked wip, and not ready for review?

Anyway, looks good except a little detail, could you remove methods in the helper that is not wrapping async calls? (I spottet at least one without a get()...)

**Comment by andersonvieiragomeslopes** [comment]
> hey @andersonvieiragomeslopes, seems like this pr is marked wip, and not ready for review?
> 
> Anyway, looks good except a little detail, could you remove methods in the helper that is not wrapping async calls? (I spottet at least one without a get()...)
> 
> The helper is really nasty, so id like to keep it as small as possible

Yes, but I will need some help to find a way to make java.util.Arrays.fill in C# I used some options like Array.Fill and others, but I think it doesn't matter much as the actual frames will be sent by another place and not this one where we are sending only "fictitious data" to illustrate the screensharing implementation.

**Comment by tompi** [comment]
@andersonvieiragomeslopes i published to nuget as version 2.4.0-beta.1.1

Let me know if anything is missing!

Again, thnx for your work, really appreciate it!

**Comment by andersonvieiragomeslopes** [comment]
Thanks :) @tompi well, I noticed that new methods (SoftwareBasedVideoFrameSender, HardwareBasedVideoFrameSender and others) are missing in the new version of the helper, I think there was a problem.

image

**Comment by tompi** [comment]
@andersonvieiragomeslopes oops, i did it again...

Check the .2 version

**Comment by andersonvieiragomeslopes** [comment]
@tompi It worked, sometimes I also have this problem when generating, do you know what the cause is?

**Pull request merged**
